export const currencys = [
  'AAVE', 'ALLFT', 'AMFT', 'ARGFT', 'ASRFT', 'ATMFT', 'AXS', 'BAL', 'BARFT', 'BAT', 'BCH', 'BTC', 'CAIFT', 'CHZ', 'CITYFT', 'COMP', 'CRV', 'DAI', 'ENJ', 'ETH', 'GALFT', 'GRT', 'JUVFT', 'KNC', 'LINK', 'LTC', 'MANA', 'MCO2', 'MKR', 'NAVIFT', 'OGFT', 'PAXG', 'PFLFT', 'PSGFT', 'REN', 'SAUBERFT', 'SNX', 'THFT', 'UMA', 'UNI', 'USDC', 'WBX', 'XRP', 'YFI', 'ZRX',
];

export const userDefault = {
  name: 'Neymar Junior',
  email: 'neymarPSG@gmail.com',
  currency: 79483000,
};

export const currencysNames = {
  AAVE: 'Aave',
  ACMFT: 'Fan Token ASR',
  ACORDO01: 'None',
  ALLFT: 'BARFT',
  AMFT: 'BARFT',
  ARGFT: 'BARFT',
  ASRFT: 'Fan Token ASR',
  ATMFT: 'Fan Token ATM',
  AXS: 'Axie Infinity Shard',
  BAL: 'Balancer',
  BARFT: 'BARFT',
  BAT: 'Basic Attention token',
  BCH: 'Bitcoin Cash',
  BTC: 'Bitcoin',
  CAIFT: 'Fan Token CAI',
  CHZ: 'Chiliz',
  CITYFT: 'BARFT',
  COMP: 'Compound',
  CRV: 'Curve',
  DAI: 'Dai',
  DAL: 'Balancer',
  ENJ: 'Enjin',
  ETH: 'Ethereum',
  GALFT: 'Fan Token GAL',
  GRT: 'The Graph',
  JUVFT: 'Fan Token JUV',
  KNC: 'Kyber Network',
  LINK: 'CHAINLINK',
  LTC: 'Litecoin',
  MANA: 'Decentraland',
  MCO2: 'MCO2',
  MKR: 'Maker',
  NAVIFT: 'BARFT',
  OGFT: 'Fan Token ASR',
  PAXG: 'PAX Gold',
  PFLFT: 'BARFT',
  PSGFT: 'Fan Token PSG',
  REI: 'Ren',
  REN: 'Ren',
  SAUBERFT: 'BARFT',
  SNX: 'Synthetix',
  THFT: 'BARFT',
  UMA: 'Uma',
  UNI: 'Uniswap',
  USDC: 'USD Coin',
  WBX: 'WiBX',
  XRP: 'XRP',
  YFI: 'Yearn',
  ZRX: '0x',
};
